build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "krseo - Developer"
    email: "krseo.dev@gmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
