loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "kreso - QA Lead"
    email: "krseo.dev@gmail.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467