spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "krseo"
    email: "krseo.dev@gmail.com"
  onCallSupport:
    - (02) 222-2222
    - 010-2222-2222